[package]
name = "shirabansyo_lang"
version = "0.1.0"
edition = "2021"

[dependencies]
assembler = { path = "./crates/assembler"}
compiler = { path = "./crates/compiler" }
anyhow = "1.0"
thiserror = "1.0"
